
service: geoapp
frameworkVersion: "3"

package:
  patterns:
    - "!./**"
    - "Handlers/**"
    - "Classes/**"
    - "Utils/**"
    - "DataBase/**"

plugins:
  - serverless-offline

useDotenv: true

provider:
  name: aws
  runtime: python3.11

functions:
  UserApi:
    handler: Handlers/UserHandler.user
    events:
      - http:
          path: /get_user
          method: get
      - http:
          path: /create_user
          method: post
      - http:
          path: /update_user
          method: put
      - http:
          path: /delete_user
          method: delete

  ChangePasswordApi:
    handler: Handlers/UserHandler.change_password
    events:
      - http:
          path: /change_password
          method: post

  AddressApi:
    handler: Handlers/AddressHandler.address
    events:
      - http:
          path: /get_address
          method: get
      - http:
          path: /create_address
          method: post
      - http:
          path: /update_address
          method: put
      - http:
          path: /delete_address
          method: delete

  DocumentTypeApi:
    handler: Handlers/DocumentTypeHandler.document_type
    events:
      - http:
          path: /get_document_types
          method: get
      - http:
          path: /create_document_type
          method: post
      - http:
          path: /update_document_type
          method: put
      - http:
          path: /delete_document_type
          method: delete

  GenderApi:
    handler: Handlers/GenderHandler.gender
    events:
      - http:
          path: /get_genders
          method: get
      - http:
          path: /create_gender
          method: post
      - http:
          path: /update_gender
          method: put
      - http:
          path: /delete_gender
          method: delete

  CityApi:
    handler: Handlers/CityHandler.city
    events:
      - http:
          path: /get_cities
          method: get
      - http:
          path: /create_city
          method: post
      - http:
          path: /update_city
          method: put
      - http:
          path: /delete_city
          method: delete

  StateApi:
    handler: Handlers/StateHandler.state
    events:
      - http:
          path: /get_states
          method: get
      - http:
          path: /create_state
          method: post
      - http:
          path: /update_state
          method: put
      - http:
          path: /delete_state
          method: delete

  BankApi:
    handler: Handlers/BankHandler.bank
    events:
      - http:
          path: /get_banks
          method: get
      - http:
          path: /create_bank
          method: post
      - http:
          path: /update_bank
          method: put
      - http:
          path: /delete_bank
          method: delete

  PaymentCardApi:
    handler: Handlers/PaymentCardHandler.payment_card
    events:
      - http:
          path: /get_user_cards
          method: get
      - http:
          path: /create_payment_card
          method: post
      - http:
          path: /update_payment_card
          method: put
      - http:
          path: /delete_payment_card
          method: delete

  EquipmentApi:
    handler: Handlers/EquipmentHandler.equipment
    events:
      - http:
          path: /get_equipment
          method: get
      - http:
          path: /create_equipment
          method: post
      - http:
          path: /update_equipment
          method: put
      - http:
          path: /delete_equipment
          method: delete

  EquipmentMaintenanceStatusApi:
    handler: Handlers/MaintenanceStatusHandler.maintenance_status
    events:
      - http:
          path: /equipment_maintenance_status
          method: get
      - http:
          path: /equipment_maintenance_status
          method: post

  AuthApi:
    handler: Handlers/AuthHandler.auth
    events:
      - http:
          path: /auth
          method: post

  UserByTokenApi:
    handler: Handlers/UserHandler.user_data_by_token
    events:
      - http:
          path: /get_user_data_by_token
          method: get

  LocationApi:
    handler: Handlers/LocationHandler.location
    events:
      - http:
          path: /location
          method: get
